---
- name: Converge
  hosts: all
  roles:
    - role: ansible-role-postgresql
      postgresql_databases:
        - name: publicdb
        - name: secretdb
          owner: alice
          restrict: true
      postgresql_users:
        - user: alice
          password: alice123
          # alice is the owner of secretdb so already has access
          databases: [publicdb]
        - user: bob
          password: bob123
          databases: [publicdb, secretdb]
          roles: "CREATEDB,NOSUPERUSER"
        - user: charles
          password: charles123
          databases: []

- hosts: all
  tasks:
    - name: create test tables publicdb
      command: >
        env PGPASSWORD=alice123 psql -h localhost -U alice publicdb
        -c "{{ item }}"
      register: result
      changed_when: >
        (not ('skipping' in result.stderr or '0 0' in result.stdout))
      with_items:
        - "create table if not exists regular (text text primary key);"
        - >
          insert into regular select ('clear text') where not exists
          (select text from regular);

    - name: create test tables secretdb
      command: >-
        env PGPASSWORD=alice123 psql -h localhost -U alice secretdb
        -c "{{ item }}"
      register: result
      changed_when: >
        (not ('skipping' in result.stderr or '0 0' in result.stdout))
      with_items:
        - "create table if not exists regular (text text primary key);"
        - >
          insert into regular select ('clear text') where not exists
          (select text from regular);
        - "create table if not exists password (text text primary key);"
        - >
          insert into password select ('PRIVATE!') where not exists
          (select text from password);

    - name: set privileges on secretdb tables
      become: true
      become_user: postgres
      postgresql_privs:
        database: "{{ item }}"
        obj: regular
        privs: SELECT
        roles: bob
        state: present
        type: table
      with_items:
        - publicdb
        - secretdb
