- hosts: localhost

  vars:
    domain: cyberwhale.tech
    ansible_user: vladimir
    run_address: 0.0.0.0
    run_port: 5000

  roles:
  - role: bihealth.python3
  - role: nginxinc.nginx
  - role: robertdebock.npm

  tasks:
  - name: "apt-get update"
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: "create root directory"
    file:
      path: /var/{{ domain }}
      state: directory
      mode: '0775'
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
  
  - name: delete default nginx site
    file:
      path: /etc/nginx/sites-enabled/default
      state: absent
    notify: restart nginx

  - name: copy nginx site.conf
    template:
      src: nginx/host.conf.j2
      dest: /etc/nginx/sites-enabled/{{ domain }}
      owner: root
      group: root
      mode: '0644'
    notify: restart nginx
  
  
  handlers:
  - name: restart nginx
    service:
      name: nginx
      state: restarted
