# Simple example relying on the default Postgres PUBLIC privileges
# which allow access to all users
- hosts: localhost
  roles:
  - role: bihealth.python3
  - role: robertdebock.npm
  - role: pg
    postgresql_version: "12"
    postgresql_server_listen: "'*'"
    postgresql_server_auth:
    - database: lda_dev
      user: postgres
      address: 192.168.1.0/24
    postgresql_databases:
    - name: lda_dev
    postgresql_users:
    - user: postgres
      password: AdvancedStuff!!#love
      databases: []